FROM python:3.10.1-slim-buster

# create dir for app user
RUN mkdir -p /home/app
# create app user
RUN addgroup --system app && adduser --system --group app
# create project dir
ENV HOME=/home/app
ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV ENVIRONMENT prod
ENV TESTING 0

# install system dependencies
RUN apt-get update \
  && apt-get -y install netcat gcc \
  && apt-get clean

# install python dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt
RUN pip install "uvicorn[standard]==0.17.0"

# add app
COPY . .

# chown all files
RUN chown -R app:app $APP_HOME

# change user
USER app

# RUN gunicorn
CMD ["./startup.sh"]

